version: '3.7'
services:

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
    networks:
      - elk

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      # - ./kafka_data/:/opt/kafka/logs/
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - elk

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    container_name: elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms750m -Xmx750m"
    volumes:
      - type: volume
        source: logs
        target: /var/log
      - type: volume
        source: esdata
        target: /usr/share/elasticsearch/data
    networks:
      - elk
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    image: docker.elastic.co/kibana/kibana:7.4.0
    container_name: kibana
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    volumes:
      - type: volume
        source: logs
        target: /var/log
    networks:
      - elk

volumes:
  esdata:
  logs:

networks:
  elk:
