version: '3.7'
services:

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
    networks:
      - elk

  kafka:
    image: wurstmeister/kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - elk

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    container_name: elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms750m -Xmx750m"
    volumes:
      - type: volume
        source: logs
        target: /var/log
      - type: volume
        source: esdata
        target: /usr/share/elasticsearch/data
    networks:
      - elk
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    image: docker.elastic.co/kibana/kibana:7.4.0
    container_name: kibana
    depends_on:
      - elasticsearch
    # environment:
    #   SERVER_NAME: localhost
    #   ELASTICSEARCH_URL: http://es:9200/
    ports:
      - 5601:5601
    volumes:
      - type: volume
        source: logs
        target: /var/log
    networks:
      - elk

  metricbeat:
    image: docker.elastic.co/beats/metricbeat:7.4.0
    user: root
    depends_on:
      - elasticsearch
      - kafka
    links:
      - kafka:kafka
    # labels:
    #   - co.elastic.metrics/module=kafka
    #   - co.elastic.metrics/metricsets=["partition","consumergroup"]
    #   - co.elastic.metrics/hosts=["localhost:9092"]
    environment:
      - setup.kibana.host=kibana:5601
      - output.elasticsearch.hosts=["elasticsearch:9200"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./metricbeat.docker.yml:/usr/share/metricbeat/metricbeat.yml:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /proc:/hostfs/proc:ro
      - /:/hostfs:ro
    command: metricbeat -e -system.hostfs=/hostfs -strict.perms=false
    networks:
      - elk

volumes:
  esdata:
  logs:
networks:
  elk:
