filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
setup.kibana.host: "kibana:5601"
# # setup.dashboards.enabled: true
filebeat.modules:
- module: kafka
  log:
    enabled: true
    var:
      kafka_home:
        - "/opt/kafka/"
    var:
      paths:
        - "/opt/kafka/controller.log*"
        - "/opt/kafka/server.log*"
        - "/opt/kafka/state-change.log*"
        - "/opt/kafka/kafka-*.log*"

processors:
- add_cloud_metadata: ~

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
